repos:
  - repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.10.1
    hooks:
      - id: check-autopkg-recipes
        args: ["--recipe-prefix=com.github.oliverweinm-recipes.", "--"]
      - id: forbid-autopkg-overrides
      - id: forbid-autopkg-trust-info
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending
